name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x' # Replace this with your .NET version

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build /p:Version=${{ steps.gitversion.outputs.majorMinorPatch }} --configuration Release --no-restore

      - name: Pack
        run: dotnet pack /p:PackageVersion=${{ steps.gitversion.outputs.semanticVersion }} --no-build --configuration Release --output out

      - name: Push
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x' # Replace this with your .NET version
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}

      - name: Publish
        run: dotnet nuget push "**/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
