name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x' # Replace this with your .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Pack
        run: dotnet pack --no-build --configuration Release --output out

      - name: Push
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x' # Replace this with your .NET version
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}

      - name: Publish
        run: dotnet nuget push "**/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
